# Generated by Django 5.1.4 on 2024-12-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_transcation_id_order_transaction_id_and_more'),
        ('store', '0005_alter_orderitem_order'),
    ]

    operations = [
    ]
